<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_imgiconosSeccionesSeguridad_2.png_ctl_ff7ba7</name>
   <tag></tag>
   <elementGuidId>9d03a903-bb11-48ef-90ab-cd4c3185e49e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_gvMenu_ImageButton3_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_gvMenu_ImageButton3_2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;cPHPri_gvMenu_ImageButton3_2&quot;)[count(. | //*[@type = 'image' and @name = 'ctl00$cPHPri$gvMenu$ctl04$ImageButton3' and @id = 'cPHPri_gvMenu_ImageButton3_2' and @title = 'Editar' and @src = '../../../Img/Iconos/editar_2.gif']) = count(//*[@type = 'image' and @name = 'ctl00$cPHPri$gvMenu$ctl04$ImageButton3' and @id = 'cPHPri_gvMenu_ImageButton3_2' and @title = 'Editar' and @src = '../../../Img/Iconos/editar_2.gif'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$gvMenu$ctl04$ImageButton3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_gvMenu_ImageButton3_2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Editar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Img/Iconos/editar_2.gif</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_gvMenu_ImageButton3_2&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_gvMenu_ImageButton3_2']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_gvMenu']/tbody/tr[3]/td[10]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[10]/input</value>
   </webElementXpaths>
</WebElementEntity>
