<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Configuracin destinos_cPHPri_TabContain_1ea7b0</name>
   <tag></tag>
   <elementGuidId>0899458c-65ef-482e-8008-1c1a25b61be4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_TabContainer1_TabPanelDestinos_MenuEdicionDestinos_imgNuevo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer1_TabPanelDestinos_MenuEdicionDestinos_imgNuevo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer1_TabPanelDestinos_MenuEdicionDestinos_imgNuevo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/Nuevo30x30_2.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer1_TabPanelDestinos_MenuEdicionDestinos_imgNuevo&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_TabContainer1_TabPanelDestinos_MenuEdicionDestinos_imgNuevo']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_TabContainer1_TabPanelDestinos_MenuEdicionDestinos_lkbNuevo']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div/div/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
