<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Configuracin parmetros a mostrar del cl_c17580</name>
   <tag></tag>
   <elementGuidId>191545bb-a4b4-498d-8380-ceaa9c857ca9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_MenuEdicionActualizar_imgActualizar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_MenuEdicionActualizar_imgActualizar</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'cPHPri_MenuEdicionActualizar_imgActualizar' and @src = '../../../img/Iconos/Edicion/Actualizar30x30_2.png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_MenuEdicionActualizar_imgActualizar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/Actualizar30x30_2.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_MenuEdicionActualizar_imgActualizar&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_MenuEdicionActualizar_imgActualizar']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_MenuEdicionActualizar_lkbActualizar']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
